site_name: Solivagant
site_url: https://hoc081098.github.io/solivagant/docs/0.x
repo_name: solivagant
repo_url: https://github.com/hoc081098/solivagant
site_description: "🔆 Compose Multiplatform Navigation - 🌸 Pragmatic, type safety navigation for Compose Multiplatform. Based on Freeletics Khonshu Navigation."
site_author: Petrus Nguyễn Thái Học
remote_branch: gh-pages
edit_uri: edit/master/docs/

copyright: 'Copyright &copy; 2024 Petrus Nguyễn Thái Học.'

theme:
  name: 'material'
  favicon: images/logo.jpeg
  logo: images/logo.jpeg
  palette:
    primary: 'deep purple'
    accent: 'white'
  features:
    - toc.integrate

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables
  - mdx_truly_sane_lists

nav:
  - 'Overview': index.md
  - 'Multiplatform': multiplatform.md
  - 'Change Log': changelog.md
  - 'API': API
